version: "3.8"

services:
  nginx:
    image: "nginx:alpine"
    ports:
      - "8002:80"
    volumes:
      - ./_docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    depends_on:
      - mysql
      - php
  php:
    build:
      context: ./_docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/laravel
  mysql:
    image: mysql:8.0
    ports:
      - "3316:3306"
    env_file:
      - ./_docker/mysql/.env
    volumes:
      - db_data:/var/lib/mysql

  artisan:
    build:
      context: ./_docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]

volumes:
  db_data: