services:
    webserver:
        image: "nginx:alpine"
        restart: unless-stopped
        ports:
            - "8002:80"
        volumes:
            - ./_docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www
        depends_on:
            - db
            - app
        container_name: laravel-webserver
        networks:
            - my-app-network

    app:
        build:
            context: ./_docker/php
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        working_dir: /var/www
        restart: unless-stopped
        environment:
            SYSTEM_USER_ID: ${SYSTEM_USER_ID:-1000}
            SYSTEM_GROUP_ID: ${SYSTEM_GROUP_ID:-1000}
        volumes:
            - ./:/var/www
        networks:
            - my-app-network

    db:
        image: mysql:8.0
        restart: unless-stopped
        ports:
            - "3316:3306"
        environment:
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            TZ: ${DB_TZ:-UTC}
        volumes:
            - db_data:/var/lib/mysql
        container_name: laravel-db
        networks:
            - my-app-network

    node:
        build:
            context: ./_docker/node
            dockerfile: Dockerfile
        image: node:20.9-alpine
        working_dir: /usr/src/app
        container_name: laravel-node
        volumes:
            - .:/usr/src/app
        ports:
            - 5173:5173
        environment:
            - NODE_ENV=development
        networks:
            - my-app-network
        restart: unless-stopped

volumes:
    db_data:
        driver: local

networks:
    my-app-network:
        driver: bridge
